# Generated by Django 3.0.3 on 2020-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landsellmodel',
            name='image',
            field=models.ImageField(blank=True, default='D:\x07tom projects\\webnew\\web1\\media\\images\\IMG_20190625_192316.jpg', null=True, upload_to='images'),
        ),
    ]
