# Generated by Django 3.0.3 on 2020-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200605_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landbuy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Buyimages/% Y/% m/% d/'),
        ),
    ]
